<a href="https://colab.research.google.com/github/drago467/DeepUnderstandingOfDeepLearning-main/blob/master/Notebook/Math/Matrix_multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import libraries
import numpy as np
import torch

In [ ]:
# create some random matrices
A = np.random.randn(3, 4)
B = np.random.randn(4, 5)
C = np.random.randn(3, 7)

# try some multiplications...
print(np.round(A @ B, 2)), print(' ')
# print(np.round(A @ C, 2)), print(' ')
# print(np.round(B @ C, 2)), print(' ')
print(np.round(C.T @ A, 2))

[[ 0.58  1.51  0.92 -1.9  -0.92]
 [ 1.12  0.44  0.84 -2.1  -1.41]
 [-0.75 -1.67  1.3   0.61 -0.09]]
 
[[ 0.14 -1.29 -2.17  0.96]
 [-0.32 -0.9  -1.97  1.65]
 [-1.02  0.69  1.21 -1.65]
 [-0.36  0.32  0.02  1.07]
 [-0.82  0.54  0.46  0.2 ]
 [ 1.27 -1.49 -2.65  2.72]
 [ 0.51 -0.8  -0.76 -0.78]]


In [ ]:
# create some random matries
A = torch.randn(3, 4)
B = torch.randn(4, 5)
C1 = np.random.randn(4, 7)
C2 = torch.tensor(C1, dtype = torch.float)

# try some multiplications..
print(np.round(A @ B, 2)), print(' ')
# print(np.round(A @ B.T, 2)), print(' ')
print(np.round(A @ C1, 2)), print(' ')
print(np.round(A @ C2, 2))

tensor([[-0.1900,  0.5700, -0.7800,  0.5600, -1.7300],
        [-3.3100,  0.0200, -2.2800,  1.8400, -2.4600],
        [ 2.2600, -0.0500,  0.8800, -1.8800,  0.9800]])
 
tensor([[ 2.5400, -1.8800,  0.7300,  0.0600, -0.0300, -0.9500, -2.3200],
        [ 2.6900, -3.9200, -2.1800,  0.5000,  3.5300, -0.8500, -3.3400],
        [-2.5900, -1.2200,  0.8400, -1.3300, -2.0600,  0.2100,  1.3900]],
       dtype=torch.float64)
 
tensor([[ 2.5400, -1.8800,  0.7300,  0.0600, -0.0300, -0.9500, -2.3200],
        [ 2.6900, -3.9200, -2.1800,  0.5000,  3.5300, -0.8500, -3.3400],
        [-2.5900, -1.2200,  0.8400, -1.3300, -2.0600,  0.2100,  1.3900]])
