<a href="https://colab.research.google.com/github/drago467/DeepUnderstandingOfDeepLearning-main/blob/master/Notebook/Math/RepoducibleRandomnessViaSeeding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# import libraries
import numpy as np
import torch

In [3]:
# generate a few random numbers
np.random.randn(5)

array([ 1.36238571, -0.95502695, -0.45847607, -1.25295266, -0.46748516])

In [5]:
# repeat after fixing the seed (old-but-still-widely-used method)
np.random.seed(17)
print(np.random.randn(5))
print(np.random.randn(5))

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]


In [6]:
randseed1 = np.random.RandomState(17)
randseed2 = np.random.RandomState(20210530)

print( randseed1.rand(5) ) # same sequence
print( randseed2.rand(5) ) # different from above, but same each time
print( randseed1.rand(5) ) # same as two up
print( randseed2.rand(5) ) # same as two up
print( np.random.randn(5) )# different every time

[0.294665   0.53058676 0.19152079 0.06790036 0.78698546]
[0.13128311 0.40968431 0.53891849 0.61951919 0.65726249]
[0.65633352 0.6375209  0.57560289 0.03906292 0.3578136 ]
[0.67593914 0.92015352 0.01978739 0.00161252 0.49311545]
[ 2.171257    1.15231025 -1.81881234 -0.13804934  0.53983961]


In [7]:
torch.randn(5)

tensor([-0.0951,  0.1724, -1.4931, -1.2865,  0.5554])

In [8]:
torch.manual_seed(17)
print( torch.randn(5) )

# torch's seed doesn't spread to numpy
print( np.random.randn(5))

tensor([-1.4135,  0.2336,  0.0340,  0.3499, -0.0145])
[-1.77528229  1.31487654 -0.47344805 -1.0922299  -0.25002744]
