In [2]:
import numpy as np

In [4]:
# create a vector
nv = np.array([[1, 2, 3, 4]])
print(nv), print(' ')

# transpose it 
print(nv.T), print(' ')

# transpose the transpose !
nvT = nv.T
print(nvT.T)

[[1 2 3 4]]
 
[[1]
 [2]
 [3]
 [4]]
 
[[1 2 3 4]]


In [ ]:
conda create -n env_pytorch python=3.6

In [ ]:
conda activate env_pytorch

In [ ]:
pip install torchvision 

In [ ]:
# create a vector
tv = torch.tensor([ [1, 2, 3, 4] ])
print(tv), print(' ')

# transpose it
print(tv.T), print(' ')

# transpose the transpose !
tvT = tv.T
print(tvT.T)

In [ ]:
# repeat for a matrix
tM  = torch.tensor([ [1, 2, 3, 4], [5, 6, 7, 8] ])
print(tM), print(' ')

# transpose it
print(tM.T), print(' ')

# transpose the transpose !
tMT = tM.T
print(tMT.T)