<a href="https://colab.research.google.com/github/drago467/DeepUnderstandingOfDeepLearning-main/blob/master/Notebook/Math/Vector_and_matrix_transpose.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import torch

In [8]:
# create a vector
nv = np.array([[1, 2, 3, 4]])
print(nv), print(' ')

# transpose it
print(nv.T), print(' ')

# transpose the transpose !
nvT = nv.T
print(nvT.T)

[[1 2 3 4]]
 
[[1]
 [2]
 [3]
 [4]]
 
[[1 2 3 4]]


In [9]:
# create a vector
tv = torch.tensor([ [1, 2, 3, 4] ])
print(tv), print(' ')

# transpose it
print(tv.T), print(' ')

# transpose the transpose !
tvT = tv.T
print(tvT.T)

tensor([[1, 2, 3, 4]])
 
tensor([[1],
        [2],
        [3],
        [4]])
 
tensor([[1, 2, 3, 4]])


In [10]:
# repeat for a matrix
tM  = torch.tensor([ [1, 2, 3, 4], [5, 6, 7, 8] ])
print(tM), print(' ')

# transpose it
print(tM.T), print(' ')

# transpose the transpose !
tMT = tM.T
print(tMT.T)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
 
tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])
 
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
